log_format stream '$remote_addr [$time_local] '
'$protocol $status $bytes_sent $bytes_received '
'$session_time';

server {
  listen 22;
  preread_by_lua_file /usr/local/openresty/nginx/lua/detect_ssh.lua;
  proxy_pass cowrie:2222;
}