server {
  listen 80;
  server_name _;

  location / {
    rewrite_by_lua_file /usr/local/openresty/nginx/lua/detect.lua;
    proxy_pass http://app:80;
  }

  location @honeypot {
    proxy_pass http://http-honeypot:80;
  }
}
