log_format stream '$remote_addr [$time_local] '
'$protocol $status $bytes_sent $bytes_received '
'$session_time';

server {
  listen 22;
  proxy_pass ssh-honeypot:2222;
}

server {
  listen 23;
  proxy_pass ssh-honeypot:2223;
}