env HOST_IP;

events {
  worker_connections 1024;
}

http {
  include mime.types;
  default_type application/octet-stream;

  resolver 8.8.8.8 ipv6=off;

  log_format custom '$remote_addr - $remote_user [$time_local] '
  '"$request" $status $body_bytes_sent '
  '"$http_referer" "$http_user_agent"';

  access_log /var/log/nginx/access_log custom;

  include /etc/nginx/conf.d/http.conf;
}

stream {
  include /etc/nginx/conf.d/stream.conf;
}