name: Security audit(dispatcher)

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
      - develop

jobs:
  audit:
    name: Security audit
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: dispatcher/paramiko

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          sparse-checkout: |
            dispatcher/paramiko

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "dispatcher/paramiko/.python-version"

      - name: Install pip-audit
        run: |
          python -m pip install .
          python -m pip install pip-audit

      - name: Audit Python dependencies
        run: pip-audit
